# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c5bf94c24573cca0fa52241e8da87d367946047767d1945d8232609dae7003d08623b061bf3a09b99efffc1139c60a57632cd9bff4c542beb5dcd892a70eec7

test:
  secret_key_base: 5be5f9cee9ea9d36ed5aff73ae31d1d2a99be38e62d8f4a0fd11282dad769941f766f2e926a42c7b8f542f4023fad9a8ce49ad202a4c3e7594b51baeaa23019c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
